---
title: "Course Project"
author: "Rose Nyameke"
date: "November 21, 2015"
output: 
  html_document: 
    keep_md: yes
---
##Data Processing
````{r load, message = FALSE}
data <- read.csv("pml-training.csv")
library(dplyr)
library(caret)
library(ggplot2)
library(gbm)
````

````{r clean data}
#keeping only the numeric variables
data_wo_factors <- data[sapply(data, is.numeric)]

#re-introducing the classe variable
data_wo_factors <- cbind(data$classe, data_wo_factors)

#removing the row numbering variable
data_wo_factors <- data_wo_factors[, -2]

#removing columns with nas
data_wo_nas <- data_wo_factors[, colSums(is.na(data_wo_factors)) == 0]

#finding highly correlated predictor variables
correlationMatrix <- cor(data_wo_nas[,-1])
highcorr <- findCorrelation(correlationMatrix, cutoff = 0.75)

#removing the highly correlated columns
data_wo_corr <- data_wo_nas[,-highcorr]

#removing the timestamp columns
data_wo_time <- data_wo_corr[, -(2:3)]

#renaming the classe column
names(data_wo_time)[1] <- "classe"

clean_data <- data_wo_time

````

````{r model, cache = TRUE}
#building model using gbm and cross-fold validation (for speed reasons)
model <- train(classe ~ ., method = "gbm", trControl = trainControl(method = "cv", number = 10),
               data = clean_data, verbose = TRUE)
````

````{r clean test data, cache = TRUE}

#predict with model
test_data <- read.csv("pml-testing.csv")

#keeping only the variables from the train data model
keepvariables <- names(clean_data)

#removing the classe variable
keepvariables <- keepvariables[-1]

#subsetting the test data
clean_test_data <- subset(test_data, select = keepvariables)

````

````{r predict}
answers <- predict(model, data = clean_test_data)

pml_write_files <- function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}

pml_write_files(answers)

````